// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkZ6cxP1UU2RML4J0Kzowrj23fl52pzdc',
    appId: '1:201045524619:web:c71bf47b0d99f9475dd48e',
    messagingSenderId: '201045524619',
    projectId: 'learningmanagementsystem-ee1d0',
    authDomain: 'learningmanagementsystem-ee1d0.firebaseapp.com',
    storageBucket: 'learningmanagementsystem-ee1d0.appspot.com',
    measurementId: 'G-G98LW9985V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs1KEvsS7CIhMPyCXi6SYK7-DqrumGvng',
    appId: '1:201045524619:android:d1e959a7d2a38dca5dd48e',
    messagingSenderId: '201045524619',
    projectId: 'learningmanagementsystem-ee1d0',
    storageBucket: 'learningmanagementsystem-ee1d0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhctx3wA_B5HFu94D77lPVnD0IGQ9-2e4',
    appId: '1:201045524619:ios:19031f62adfb7b475dd48e',
    messagingSenderId: '201045524619',
    projectId: 'learningmanagementsystem-ee1d0',
    storageBucket: 'learningmanagementsystem-ee1d0.appspot.com',
    androidClientId: '201045524619-s9l4qvui9b5m5tr1uvs3g7142ehtsnph.apps.googleusercontent.com',
    iosClientId: '201045524619-501f8kt2n4jd8cg14thbpnkn7dbnot0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhctx3wA_B5HFu94D77lPVnD0IGQ9-2e4',
    appId: '1:201045524619:ios:19031f62adfb7b475dd48e',
    messagingSenderId: '201045524619',
    projectId: 'learningmanagementsystem-ee1d0',
    storageBucket: 'learningmanagementsystem-ee1d0.appspot.com',
    androidClientId: '201045524619-s9l4qvui9b5m5tr1uvs3g7142ehtsnph.apps.googleusercontent.com',
    iosClientId: '201045524619-501f8kt2n4jd8cg14thbpnkn7dbnot0h.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFcm',
  );
}
